# Generated by Django 3.2.16 on 2024-02-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240209_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='Если установить дату и время вбудущем — можно делатьотложенные публикации.', verbose_name='Дата и время публикации'),
        ),
    ]
